export const INDUSTRY_KEYWORDS: Record<string, string[]> = {
  skincare: ["serum", "kem dưỡng", "mụn", "da", "skincare", "dưỡng trắng", "chống nắng", "cấp ẩm"],
  makeup: ["son", "phấn", "makeup", "mascara", "kem nền", "mắt", "má hồng"],
  spa: ["spa", "massage", "facial", "chăm sóc da", "liệu trình"],
  hair_salon: ["tóc", "hair", "salon", "uốn", "nhuộm", "cắt tóc"],
  nail: ["nail", "móng", "sơn gel"],
  clinic: ["clinic", "thẩm mỹ", "laser", "nâng cơ", "trị liệu"],
  perfume: ["nước hoa", "perfume", "hương thơm"],
  organic_beauty: ["organic", "thiên nhiên", "lành tính", "herbal"],
  anti_aging: ["lão hóa", "nếp nhăn", "trẻ hóa", "anti aging"],
  acne_treatment: ["mụn", "trị mụn", "acne", "thâm mụn"],
  fast_food: ["burger", "gà rán", "pizza", "fast food", "combo"],
  cafe: ["cafe", "cà phê", "espresso", "latte"],
  milk_tea: ["trà sữa", "milk tea", "trân châu"],
  fine_dining: ["fine dining", "nhà hàng", "set menu", "sang trọng"],
  street_food: ["ăn vặt", "street food", "bánh tráng", "xiên que"],
  healthy_food: ["healthy", "eat clean", "salad", "calo"],
  bakery: ["bánh", "bakery", "croissant", "bánh mì"],
  bbq: ["bbq", "nướng", "thịt nướng"],
  seafood: ["hải sản", "seafood", "tôm", "cua"],
  dessert: ["dessert", "kem", "bánh ngọt", "chè"],
  streetwear: ["streetwear", "áo thun", "hoodie", "sneaker"],
  luxury_fashion: ["luxury fashion", "đầm dạ hội", "cao cấp", "lụa"],
  local_brand: ["local brand", "brand việt", "áo local"],
  sportswear: ["gymwear", "sportswear", "đồ tập"],
  kids_fashion: ["kids", "trẻ em", "bé trai", "bé gái"],
  office_wear: ["office wear", "công sở", "áo sơ mi"],
  vintage: ["vintage", "retro", "secondhand"],
  minimal: ["minimal", "tối giản", "basic"],
  apartment: ["căn hộ", "chung cư", "apartment"],
  townhouse: ["nhà phố", "townhouse"],
  villa: ["biệt thự", "villa"],
  land: ["đất nền", "sổ đỏ", "đầu tư đất"],
  rental: ["cho thuê", "rental", "thuê nhà"],
  online_course: ["khóa học", "course", "học online"],
  coaching: ["coaching", "mentor", "huấn luyện"],
  marketing_service: ["marketing", "agency", "ads", "quảng cáo"],
  saas: ["saas", "app", "phần mềm", "dashboard", "automation"],
  app: ["ứng dụng", "mobile app", "app"],
  freelance: ["freelance", "dịch vụ tự do"],
  mmo: ["mmo", "kiếm tiền online", "affiliate"],
  car: ["ô tô", "xe hơi", "car"],
  motorbike: ["xe máy", "motorbike"],
  gym: ["gym", "fitness", "tập luyện"],
  yoga: ["yoga", "thiền", "pilates"],
  travel: ["du lịch", "tour", "resort"],
  wedding: ["wedding", "cưới", "chụp cưới"],
  event: ["event", "sự kiện", "tổ chức"],
  interior: ["nội thất", "sofa", "bàn ghế"],
  education: ["giáo dục", "học sinh", "gia sư", "luyện thi"],
  finance: ["tài chính", "đầu tư", "vay", "bảo hiểm"],
};
