"""template_tournament — schemas for the Template Promotion Policy and Candidate Tournament System."""
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class TemplateCandidateState(BaseModel):
    """Runtime state of a single template inside the tournament lifecycle.

    Lifecycle statuses
    ------------------
    candidate        → newly generated by evolution engine
    queued_for_test  → selected for an upcoming test slot
    testing          → currently being A/B tested against production
    qualified        → passed round-1 qualification (avg ≥ 75, n ≥ 3)
    promoted         → entered the selector as an official option
    incumbent        → currently the strongest template for this bracket
    declining        → incumbent whose recent performance is dropping
    retired          → removed from automatic selection
    rejected         → failed qualification threshold
    """

    template_id: str
    template_family: str | None = None
    lifecycle_status: str = "candidate"
    market_code: str | None = None
    content_goal: str | None = None
    topic_class: str | None = None
    episode_role: str | None = None
    sample_count: int = 0
    average_score: float = 0.0
    stability_score: float = 0.0
    metadata: dict[str, Any] = Field(default_factory=dict)


class TournamentMatchResult(BaseModel):
    """Outcome of a single challenger-vs-incumbent match."""

    incumbent_template_id: str
    challenger_template_id: str
    incumbent_score: float
    challenger_score: float
    delta: float
    decision: str  # challenger_promoted_to_incumbent | challenger_promoted | keep_weighted_routing | incumbent_retained


class RoutingDecision(BaseModel):
    """Weighted routing split returned by TemplateRoutingPolicy."""

    bracket_key: str
    incumbent_weight: float
    challenger_weight: float
    reason: str
